### ISSUE TITLE
Creation of the Problem return type

### ISSUE THREAD

**Issue by RobertClapham** [matthewrosse/ErrorOrAspNetCoreExtensions#1]
Very nice little library thank you.

I am just wondering if the creation of the TypedResults.Problem would benefit from the introduction of the error.Code as well, giving more information to the end user depending on how the error.Code is used making it easier to track the location of the error. For example I use the error.Code in a format of ClassName.ErrorName

Currently the code is 
return TypedResults.Problem(statusCode: statusCode, title: error.Description); 

a possible solution could be 

return TypedResults.Problem(statusCode: statusCode, title: error.Description, detail: error.Code); 

an even better solution could be to use error.Code in the title because it should never change  and error.Description in the detail much like the detailed being logged with a human readable description of the prblem.

return TypedResults.Problem(statusCode: statusCode, detail: error.Description, title: error.Code);

**Comment by matthewrosse** [comment]
Resolved with #2, thank you for the contribution!
